-- MySQL Script generated by MySQL Workbench
-- Mon Aug 10 11:47:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Groupomania_sqldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Groupomania_sqldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Groupomania_sqldb` DEFAULT CHARACTER SET utf8 ;
USE `Groupomania_sqldb` ;

-- -----------------------------------------------------
-- Table `Groupomania_sqldb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania_sqldb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prénom` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Departement_entreprise` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Groupomania_sqldb`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania_sqldb`.`Articles` (
  `idArticles` INT NOT NULL AUTO_INCREMENT,
  `Contenu` LONGTEXT NOT NULL,
  `time_stamp` TIMESTAMP(6) NOT NULL,
  `auteur_id` INT NOT NULL,
  PRIMARY KEY (`idArticles`),
  INDEX `fk_Articles_User_idx` (`auteur_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_User`
    FOREIGN KEY (`auteur_id`)
    REFERENCES `Groupomania_sqldb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Groupomania_sqldb`.`Share`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania_sqldb`.`Share` (
  `User_idUser` INT NOT NULL,
  `Articles_idArticles` INT NOT NULL,
  `commentaire` LONGTEXT NULL,
  PRIMARY KEY (`User_idUser`, `Articles_idArticles`),
  INDEX `fk_User_has_Articles_Articles1_idx` (`Articles_idArticles` ASC) VISIBLE,
  INDEX `fk_User_has_Articles_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Articles_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Groupomania_sqldb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Articles_Articles1`
    FOREIGN KEY (`Articles_idArticles`)
    REFERENCES `Groupomania_sqldb`.`Articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Groupomania_sqldb`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania_sqldb`.`commentaires` (
  `contenu` LONGTEXT NOT NULL,
  `Articles_idArticles` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`Articles_idArticles`, `User_idUser`),
  INDEX `fk_commentaires_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_commentaires_Articles1`
    FOREIGN KEY (`Articles_idArticles`)
    REFERENCES `Groupomania_sqldb`.`Articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaires_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Groupomania_sqldb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
